# Generated by Django 3.0.1 on 2020-01-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario_lancador', models.IntegerField(null=True)),
                ('id_usuario_receptor', models.IntegerField(null=True)),
                ('chat_text', models.TextField(max_length=5000, null=True)),
                ('proposta_aceita', models.DateTimeField(auto_now_add=True)),
                ('endereco_url', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
