# Generated by Django 3.0.1 on 2020-01-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='id_usuario_item_lancador',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='id_usuario_item_receptor',
            field=models.IntegerField(null=True),
        ),
    ]
