# Generated by Django 3.0.1 on 2020-01-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200114_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='categorias_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='categorias_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='descricao_1',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='descricao_2',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='imagem1_1',
            field=models.ImageField(max_length=30, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='imagem1_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='imagem2_1',
            field=models.ImageField(max_length=30, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='imagem2_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='imagem3_1',
            field=models.ImageField(max_length=30, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='imagem3_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='imagem4_1',
            field=models.ImageField(max_length=30, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='imagem4_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='imagem5_1',
            field=models.ImageField(max_length=30, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='imagem5_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='latitude_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='latitude_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='longitude_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='longitude_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='titulo_1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='titulo_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='visualizado_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='visualizado_2',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
